/****************************************** CREACION DE TABLAS TEMPORALES Y ST ******************************************/

DROP TABLE XTMPINDDL_TMP;
DROP TABLE XINDDL_ST_LOG;
--DROP TABLE XINDDL_ST;



CREATE TABLE XTMPINDDL_TMP(
FECHA VARCHAR(12),
PERIODO NUMBER,
ANIO NUMBER,
MES NUMBER,
GRUPO_IND VARCHAR(30),
INDICADOR VARCHAR (70),
PAIS VARCHAR (20),
CENTRO VARCHAR(30),
RUTA VARCHAR(30),
VALOR_MES NUMBER,
VALOR_MES_ANTERIOR NUMBER,
VALOR_ACUMULADO NUMBER,
VALOR_ACUMULADO_AA NUMBER,
UNIDAD VARCHAR(50)
);


CREATE TABLE XINDDL_ST_LOG(
FECHA VARCHAR(12),
PERIODO NUMBER,
ANIO NUMBER,
MES NUMBER,
GRUPO_IND VARCHAR(30),
INDICADOR VARCHAR (70),
PAIS VARCHAR (20),
CENTRO VARCHAR(30),
RUTA VARCHAR(30),
UNIDAD VARCHAR(50),
VALOR NUMBER);




