/****************************************** CARGA TABLA TEMPORAL DL  ******************************************/
INSERT INTO XTMPINDDL_TMP
SELECT 
FECHA,
SUBSTR(FECHA,7,4)||SUBSTR(FECHA,4,2),
SUBSTR(FECHA,7,4),
SUBSTR(FECHA,4,2),
GRUPO_IND,
INDICADOR,
PAIS,
CENTRO,
RUTA,
VALOR_MENSUAL,
NULL,
VALOR_MENSUAL,
NULL,
VALOR_UNIDAD
FROM XTMPINDDL
ORDER BY 2;
COMMIT;


/****************************************** CALCULOS DE VALORES MENSUALES  ******************************************/

          /****** CALCULA VALOR DEL A�O ANTERIOR VOLUMEN ******/

          UPDATE XTMPINDDL_TMP TMP SET TMP.VALOR_ACUMULADO_AA=( 
          SELECT SUM(VALOR_ACUMULADO)  
          FROM XINDDL_ST ST  
          WHERE nvl(ST.ANIO,0)= nvl(TMP.ANIO-1,0) 
          AND nvl(ST.MES,0)= nvl(TMP.MES,0)
          AND nvl(ST.PAIS,0)=nvl(TMP.PAIS,0)
          AND nvl(ST.GRUPO_IND,0)=nvl(TMP.GRUPO_IND,0)
          AND nvl(ST.INDICADOR,0)=nvl(TMP.INDICADOR,0) 
          AND nvl(ST.CENTRO,0)=nvl(TMP.CENTRO,0)
          AND nvl(ST.RUTA,0)=nvl(TMP.RUTA,0));
          COMMIT;
          
          
          /****** CALCULA VALOR DEL MES ANTERIOR VOLUMEN (SIN ENERO)******/
          
          UPDATE XTMPINDDL_TMP TMP SET TMP.VALOR_MES_ANTERIOR=( 
          SELECT SUM(VALOR_MES)  
          FROM XINDDL_ST ST  
          WHERE nvl(ST.PERIODO,0)= nvl(TMP.PERIODO-1,0) 
          AND nvl(ST.PAIS,0)=nvl(TMP.PAIS,0)
          AND nvl(ST.GRUPO_IND,0)=nvl(TMP.GRUPO_IND,0)
          AND nvl(ST.INDICADOR,0)=nvl(TMP.INDICADOR,0) 
          AND nvl(ST.CENTRO,0)=nvl(TMP.CENTRO,0)
          AND nvl(ST.RUTA,0)=nvl(TMP.RUTA,0))
          WHERE MES!=1;
          COMMIT;
          
          /****** CALCULA VALOR DEL MES ANTERIOR VOLUMEN (SOLO ENERO)******/

          UPDATE XTMPINDDL_TMP TMP SET TMP.VALOR_MES_ANTERIOR=( 
          SELECT SUM(VALOR_MES)  
          FROM XINDDL_ST ST  
          WHERE nvl(ST.ANIO,0)= nvl(TMP.ANIO-1,0) 
          AND nvl(ST.MES,0)=12
          AND nvl(ST.PAIS,0)=nvl(TMP.PAIS,0)
          AND nvl(ST.GRUPO_IND,0)=nvl(TMP.GRUPO_IND,0)
          AND nvl(ST.INDICADOR,0)=nvl(TMP.INDICADOR,0) 
          AND nvl(ST.CENTRO,0)=nvl(TMP.CENTRO,0)
          AND nvl(ST.RUTA,0)=nvl(TMP.RUTA,0))
          WHERE MES=1;
          COMMIT;
          
/****** ELIMINA REGISTROS EXISTENTES DE TABLA ST **********/    
    
          
DELETE FROM XINDDL_ST ST WHERE EXISTS ( 
SELECT  (1) FROM  XTMPINDDL_TMP TMP
WHERE nvl(ST.ANIO,0)= nvl(TMP.ANIO,0) 
AND nvl(ST.MES,0)= nvl(TMP.MES,0)
AND nvl(ST.PAIS,0)=nvl(TMP.PAIS,0)
AND nvl(ST.GRUPO_IND,0)=nvl(TMP.GRUPO_IND,0)
AND nvl(ST.INDICADOR,0)=nvl(TMP.INDICADOR,0) 
AND nvl(ST.CENTRO,0)=nvl(TMP.CENTRO,0)
AND nvl(ST.RUTA,0)=nvl(TMP.RUTA,0));
COMMIT;


/****** INSERTA REGISTROS A TABLA ST **********/

INSERT INTO XINDDL_ST
SELECT * FROM XTMPINDDL_TMP;
COMMIT;



/****** REGENERA TABLAS TEMPORALES **********/

DROP TABLE XTMPINDDL_TMP_FACT;

DROP TABLE XINDDL_ST_FACT;


CREATE TABLE XTMPINDDL_TMP_FACT (
  "ID_INDICADOR" VARCHAR2(70 BYTE), 
	"FECHA" VARCHAR2(12 BYTE), 
	"PERIODO" VARCHAR2(8 BYTE), 
	"PAIS" VARCHAR2(20 BYTE), 
	"PLANTA" VARCHAR2(30 BYTE), 
	"RUTA" VARCHAR2(30 BYTE),  
	"IND_UM1" NUMBER, 
  "IND_UM2" NUMBER, 
	"UNIDAD" VARCHAR2(50 BYTE), 
	"FLAG" VARCHAR2(5 BYTE),
  "TIPO" VARCHAR2(20 BYTE)
);


CREATE TABLE XINDDL_ST_FACT (
  "FECHA" VARCHAR2(12 BYTE), 
	"PERIODO" VARCHAR2(8 BYTE), 
	"PAIS" VARCHAR2(20 BYTE), 
	"PLANTA" VARCHAR2(50 BYTE), 
	"RUTA" VARCHAR2(30 BYTE), 
	"UNIDAD" VARCHAR2(50 BYTE), 
	"NIVEL" VARCHAR2(20 BYTE),
  "TIPO" VARCHAR2(20 BYTE),
  COSTO_CU_FLETEADA NUMBER,
  COSTO_CU_FLETEADA_PA NUMBER,
  DIAS_PISO_PT NUMBER,
  DIAS_PISO_PT_PA NUMBER,
  PORCENTAJE_ABASTO NUMBER,
  PORCENTAJE_ABASTO_PA NUMBER,
  PRODUCTIVIDAD NUMBER,
  PRODUCTIVIDAD_PA NUMBER,
  TIEMPO_ESTANCIA_EN_PLANTAS NUMBER,
  TIEMPO_ESTANCIA_EN_PLANTAS_PA NUMBER,
  "EFECTIVIDAD_DISTRIBUCION" NUMBER, 
  "EFECTIVIDAD_DISTRIBUCION_PA" NUMBER,
  "PRODUCTIVIDAD_RUTA" NUMBER, 
  "PRODUCTIVIDAD_RUTA_PA" NUMBER, 
  EFICIENCIA_VISITA NUMBER,
  EFICIENCIA_VISITA_PA NUMBER,
  VISITAS_POR_DIA NUMBER,
  VISITAS_POR_DIA_PA NUMBER,
  DROP_SIZE NUMBER,
  DROP_SIZE_PA NUMBER,
  TIEMPO_EN_MERCADO NUMBER,
  TIEMPO_EN_MERCADO_PA NUMBER,
  UTILIZACION_VEHICULAR NUMBER,
  UTILIZACION_VEHICULAR_PA NUMBER,
  "MERMA_OPERACIONAL" NUMBER, 
  "MERMA_OPERACIONAL_PA" NUMBER,
  COSTO_DE_MERMA NUMBER,
  COSTO_DE_MERMA_PA NUMBER,
  PRODUCTIVIDAD_BODEGA NUMBER,
  PRODUCTIVIDAD_BODEGA_PA NUMBER,
  TIEMPO_ESTANCIA NUMBER,
  TIEMPO_ESTANCIA_PA NUMBER,
  PORCENTAJE_UTILIZACION NUMBER,
  PORCENTAJE_UTILIZACION_PA NUMBER,
  IMPACTO_GASTO_MANT_A_VTAS NUMBER,
  IMPACTO_GASTO_MANT_A_VTAS_PA NUMBER,
  IMPACTO_GASTO_COMBUSTIBLE_VTAS NUMBER,
  IMPACTO_GASTO_COMBUST_VTAS_PA NUMBER,
  DISPONIBILIDAD_FLOTA NUMBER,
  DISPONIBILIDAD_FLOTA_PA NUMBER,
  MARGEN_DISPONIBILIDAD_FLOTA NUMBER,
  MARGEN_DISPONIBILIDAD_FLOTA_PA NUMBER,
  FATAL_VEHICULOS_VENTA NUMBER,
  FATAL_VEHICULOS_VENTA_PA NUMBER,
  FATAL_VEHICULOS_VENTA_T2 NUMBER,
  FATAL_VEHICULOS_VENTA_T2_PA NUMBER,
  EFICIENCIA_COMBUSTIBLE NUMBER,
  EFICIENCIA_COMBUSTIBLE_PA NUMBER
);


/****** INSERTA DATOS TEMPORTALES INDICADORES DT **********/
INSERT INTO XTMPINDDL_TMP_FACT
SELECT 
INDICADOR, 
FECHA, 
PERIODO, 
PAIS, 
CENTRO, 
RUTA,
VALOR_MES,
VALOR_MES_ANTERIOR,
UNIDAD,
NULL,
'Actual'
FROM XINDDL_ST;
COMMIT;

INSERT INTO XTMPINDDL_TMP_FACT
SELECT 
INDICADOR, 
FECHA, 
PERIODO, 
PAIS, 
CENTRO, 
RUTA,
VALOR_ACUMULADO,
VALOR_ACUMULADO_AA,
UNIDAD,
NULL,
'Acumulado'
FROM XINDDL_ST;
COMMIT;

/****** ACTUALIZA ID Y FLAG DE ACUERDO AL INDICADOR **********/

UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='1', FLAG='1' WHERE ID_INDICADOR LIKE 'Freight Cost T1 per UC';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='2', FLAG='1' WHERE ID_INDICADOR LIKE 'Days of Inventory';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='3', FLAG='1' WHERE ID_INDICADOR LIKE '% Supply';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='4', FLAG='1' WHERE ID_INDICADOR LIKE 'T1 Productivity';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='5', FLAG='1' WHERE ID_INDICADOR LIKE 'Stay T1 Time in plants';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='6', FLAG='1' WHERE ID_INDICADOR LIKE 'Delivery Effectiveness';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='7', FLAG='1' WHERE ID_INDICADOR LIKE 'Route productivity';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='8', FLAG='1' WHERE ID_INDICADOR LIKE 'Visit Efficiency';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='9', FLAG='1' WHERE ID_INDICADOR LIKE 'T2 Visits per Day';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='10', FLAG='1' WHERE ID_INDICADOR LIKE 'Drop Size';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='11', FLAG='1' WHERE ID_INDICADOR LIKE 'Market Time';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='12', FLAG='1' WHERE ID_INDICADOR LIKE 'Vehicle Utilization';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='13', FLAG='1' WHERE ID_INDICADOR LIKE 'Thousand Index for wastes';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='14', FLAG='1' WHERE ID_INDICADOR LIKE 'Wastes Cost';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='15', FLAG='1' WHERE ID_INDICADOR LIKE 'Warehouse Productivity';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='16', FLAG='1' WHERE ID_INDICADOR LIKE 'Stay T1 Time in DC';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='17', FLAG='1' WHERE ID_INDICADOR LIKE '% Warehouse Utilization';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='18', FLAG='1' WHERE ID_INDICADOR LIKE 'Maintenance expense impact on Revenues';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='19', FLAG='1' WHERE ID_INDICADOR LIKE 'Fuel expense impact on Revenues';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='20', FLAG='1' WHERE ID_INDICADOR LIKE 'Fleet availability';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='21', FLAG='1' WHERE ID_INDICADOR LIKE 'Fleet availability margin';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='22', FLAG='1' WHERE ID_INDICADOR LIKE 'KOF sales and support vehicles related fatalities';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='23', FLAG='1' WHERE ID_INDICADOR LIKE 'KOF T2 vehicles related fatalities';
UPDATE XTMPINDDL_TMP_FACT SET ID_INDICADOR='24', FLAG='1' WHERE ID_INDICADOR LIKE 'T2 Fuel Efficiency';
COMMIT;

/****** BORRA REGISTROS DE INDICADORES NO CONSIDERADOS **********/
DELETE FROM XTMPINDDL_TMP_FACT WHERE FLAG IS NULL;
COMMIT;

UPDATE XTMPINDDL_TMP_FACT SET UNIDAD=NULL;
COMMIT;

/****** INSERTA RESULTADO EN TABLA ST, CON AJUSTE PARA INDICADORES **********/
INSERT INTO XINDDL_ST_FACT 
SELECT * FROM XTMPINDDL_TMP_FACT 
PIVOT (SUM(IND_UM1) AS ACTUAL, SUM(IND_UM2) AS ANTERIOR  FOR (ID_INDICADOR) IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24));
COMMIT;



/****** ASIGNA EL NIVEL DE INFORMACION QUE REPRESENTA CADA REGISTRO **********/

UPDATE XINDDL_ST_FACT SET NIVEL=NULL;
COMMIT;

UPDATE XINDDL_ST_FACT SET NIVEL='Pais' WHERE NOT PAIS IS NULL AND PLANTA IS NULL AND RUTA IS NULL ;
COMMIT;

UPDATE XINDDL_ST_FACT SET NIVEL='Planta' WHERE NOT PAIS IS NULL AND NOT PLANTA IS NULL AND RUTA IS NULL;
COMMIT;

UPDATE XINDDL_ST_FACT SET NIVEL='Ruta' WHERE NOT PAIS IS NULL AND NOT  PLANTA IS NULL AND NOT RUTA IS NULL;
COMMIT;

-------------------------------

/****** INSERTA DATOS DUPLICADOS DE INDICADORES DL **********/


INSERT INTO XINDDL_ST_LOG
SELECT FECHA, PERIODO, ANIO, MES, GRUPO_IND, INDICADOR, PAIS, CENTRO, RUTA, UNIDAD, VALOR FROM(
SELECT FECHA, PERIODO, ANIO, MES, GRUPO_IND, INDICADOR, PAIS, CENTRO, RUTA, UNIDAD, SUM(VALOR) AS VALOR FROM (
SELECT  1 AS VALOR, FECHA, PERIODO, ANIO, MES, GRUPO_IND, INDICADOR, PAIS, CENTRO, RUTA, UNIDAD from XINDDL_ST)
A GROUP BY FECHA, PERIODO, ANIO, MES, GRUPO_IND, INDICADOR, PAIS, CENTRO, RUTA, UNIDAD)
B WHERE VALOR>1 ORDER BY 1,2,3,4,5,6,7,8,9,10;
COMMIT;


