/****** ELIMINA TABLA FACT **********/

DROP TABLE FACT_INDICADORES_DCS;


/****** REGENERA TABLA FACT INDICADORES DL **********/

CREATE TABLE FACT_INDICADORES_DCS (
  "PK_REGISTRO" NUMBER(*,0),
  "FK_FECHA" NUMBER(*,0), 
	"FK_PAIS" NUMBER(*,0), 
	"FK_PLANTA" NUMBER(*,0), 
	"FK_RUTA" NUMBER(*,0), 
	"FK_NIVEL" NUMBER(*,0),
  "FK_TIPO" NUMBER(*,0),
  MD_PRODUCTIVIDAD NUMBER,
  MD_PRODUCTIVIDAD_PA NUMBER,
  MD_TIEM_ESTANCIA_EN_PLANTAS NUMBER,
  MD_TIEM_ESTANCIA_EN_PLANTAS_PA NUMBER,
  "MD_EFECTIVIDAD_DISTRIBUCION" NUMBER, 
  "MD_EFECTIVIDAD_DISTRIBUCION_PA" NUMBER,
  "MD_PRODUCTIVIDAD_RUTA" NUMBER, 
  "MD_PRODUCTIVIDAD_RUTA_PA" NUMBER, 
  MD_EFICIENCIA_VISITA NUMBER,
  MD_EFICIENCIA_VISITA_PA NUMBER,
  MD_VISITAS_POR_DIA NUMBER,
  MD_VISITAS_POR_DIA_PA NUMBER,
  MD_DROP_SIZE NUMBER,
  MD_DROP_SIZE_PA NUMBER,
  MD_TIEMPO_EN_MERCADO NUMBER,
  MD_TIEMPO_EN_MERCADO_PA NUMBER,
  MD_UTILIZACION_VEHICULAR NUMBER,
  MD_UTILIZACION_VEHICULAR_PA NUMBER,
  "MD_MERMA_OPERACIONAL" NUMBER, 
  "MD_MERMA_OPERACIONAL_PA" NUMBER,
  MD_COSTO_DE_MERMA NUMBER,
  MD_COSTO_DE_MERMA_PA NUMBER,
  MD_PRODUCTIVIDAD_BODEGA NUMBER,
  MD_PRODUCTIVIDAD_BODEGA_PA NUMBER,
  MD_TIEMPO_ESTANCIA NUMBER,
  MD_TIEMPO_ESTANCIA_PA NUMBER,
  MD_PORCENTAJE_UTILIZACION NUMBER,
  MD_PORCENTAJE_UTILIZACION_PA NUMBER,
  MD_IMPAC_GASTO_MANT_A_VTAS NUMBER,
  MD_IMPAC_GASTO_MANT_A_VTAS_PA NUMBER,
  MD_IMPACTO_GASTO_COMBUST_VTAS NUMBER,
  MD_IMPAC_GASTO_COMBUST_VTAS_PA NUMBER,
  MD_DISPONIBILIDAD_FLOTA NUMBER,
  MD_DISPONIBILIDAD_FLOTA_PA NUMBER,
  MD_MARGEN_DISPO_FLOTA NUMBER,
  MD_MARGEN_DISPO_FLOTA_PA NUMBER,
  MD_FATAL_VEHICULOS_VENTA NUMBER,
  MD_FATAL_VEHICULOS_VENTA_PA NUMBER,
  MD_FATAL_VEHICULOS_VENTA_T2 NUMBER,
  MD_FATAL_VEHICULOS_VENTA_T2_PA NUMBER,
  MD_EFICIENCIA_COMBUSTIBLE NUMBER,
  MD_EFICIENCIA_COMBUSTIBLE_PA NUMBER,
	CONSTRAINT PK_REGISTRO_3 PRIMARY KEY (PK_REGISTRO),
  CONSTRAINT FECHA_FK_3 FOREIGN KEY(FK_FECHA) REFERENCES DIM_TIEMPO(ID_TIEMPO),
  CONSTRAINT PAIS_FK_3 FOREIGN KEY(FK_PAIS) REFERENCES DIM_PAISES (PK_PAIS),
  CONSTRAINT PLANTA_FK_3 FOREIGN KEY(FK_PLANTA) REFERENCES DIM_PLANTAS (PK_PLANTA),
  CONSTRAINT RUTA_FK_3 FOREIGN KEY(FK_RUTA) REFERENCES DIM_RUTAS (PK_RUTA),
  CONSTRAINT NIVEL_FK_3 FOREIGN KEY(FK_NIVEL) REFERENCES DIM_NIVEL_INFO (PK_NIVEL),
  CONSTRAINT TIPO_FK_3 FOREIGN KEY(FK_TIPO) REFERENCES DIM_TIPO_DATOS (PK_TIPO)
);


/****** REGENERA SECUENCIAS FACT **********/

DROP SEQUENCE SEQ_PK_FACT_INDICADORES_DCS;

CREATE SEQUENCE SEQ_PK_FACT_INDICADORES_DCS
START WITH 1
INCREMENT BY 1 
NOMAXVALUE ;



INSERT INTO FACT_INDICADORES_DCS
SELECT 
  SEQ_PK_FACT_INDICADORES_DCS.NEXTVAL,
  NVL(PERIODO,0),
  NVL(DP.PK_PAIS,0),
  NVL(DPL.PK_PLANTA,0),
  NVL(DL.PK_RUTA,0),
  NVL(DNI.PK_NIVEL,0),
  NVL(DTD.PK_TIPO,0),
	PRODUCTIVIDAD,
  PRODUCTIVIDAD_PA,
  TIEMPO_ESTANCIA_EN_PLANTAS,
  TIEMPO_ESTANCIA_EN_PLANTAS_PA,
  "EFECTIVIDAD_DISTRIBUCION", 
  "EFECTIVIDAD_DISTRIBUCION_PA",
  "PRODUCTIVIDAD_RUTA", 
  "PRODUCTIVIDAD_RUTA_PA", 
  EFICIENCIA_VISITA,
  EFICIENCIA_VISITA_PA,
  VISITAS_POR_DIA,
  VISITAS_POR_DIA_PA,
  DROP_SIZE,
  DROP_SIZE_PA,
  TIEMPO_EN_MERCADO,
  TIEMPO_EN_MERCADO_PA,
  UTILIZACION_VEHICULAR,
  UTILIZACION_VEHICULAR_PA,
  "MERMA_OPERACIONAL", 
  "MERMA_OPERACIONAL_PA",
  COSTO_DE_MERMA,
  COSTO_DE_MERMA_PA,
  PRODUCTIVIDAD_BODEGA,
  PRODUCTIVIDAD_BODEGA_PA,
  TIEMPO_ESTANCIA,
  TIEMPO_ESTANCIA_PA,
  PORCENTAJE_UTILIZACION,
  PORCENTAJE_UTILIZACION_PA,
  IMPACTO_GASTO_MANT_A_VTAS,
  IMPACTO_GASTO_MANT_A_VTAS_PA,
  IMPACTO_GASTO_COMBUSTIBLE_VTAS,
  IMPACTO_GASTO_COMBUST_VTAS_PA,
  DISPONIBILIDAD_FLOTA,
  DISPONIBILIDAD_FLOTA_PA,
  MARGEN_DISPONIBILIDAD_FLOTA,
  MARGEN_DISPONIBILIDAD_FLOTA_PA,
  FATAL_VEHICULOS_VENTA,
  FATAL_VEHICULOS_VENTA_PA,
  FATAL_VEHICULOS_VENTA_T2,
  FATAL_VEHICULOS_VENTA_T2_PA,
  EFICIENCIA_COMBUSTIBLE,
  EFICIENCIA_COMBUSTIBLE_PA
FROM XINDDL_ST_FACT ST
LEFT JOIN DIM_PAISES DP
ON ST.PAIS=DP.GV_PAIS
LEFT JOIN DIM_PLANTAS DPL
ON ST.PLANTA=DPL.GV_PLANTA
LEFT JOIN DIM_RUTAS DL
ON ST.RUTA=DL.GV_RUTA
LEFT JOIN DIM_NIVEL_INFO DNI
ON ST.NIVEL=DNI.GV_NIVEL
LEFT JOIN DIM_TIPO_DATOS DTD
ON ST.TIPO=DTD.GV_TIPO_DATO;
COMMIT;

EXIT;