TRUNCATE TABLE FACT_DCS_FLOTA;
COMMIT;

--ELIMINA REGISTROS DUPLICADOS DE LA ST
DELETE FROM XINDDL_ST_FLOTA ST WHERE EXISTS ( 
SELECT  (1) FROM  XTMPINDDL_FLOTA TMP
WHERE nvl(ST.ANIO,0)= nvl(TMP.ANIO,0) 
AND nvl(ST.PAIS,0)=nvl(TMP.PAIS,0)
AND nvl(ST.TIPO,0)=nvl(TMP.TIPO,0)
AND nvl(ST.EDAD,0)=nvl(TMP.EDAD,0));
COMMIT;

--INSERTA DATOS EN LA ST
INSERT INTO XINDDL_ST_FLOTA
SELECT ANIO,PAIS,TIPO,EDAD,CANTIDAD FROM XTMPINDDL_FLOTA;
COMMIT;


/****** CARGA DE CATALOGO TIPO DE FLOTA **********/

MERGE INTO DIM_TIPO D
USING (SELECT DISTINCT TIPO FROM XINDDL_ST_FLOTA WHERE NOT TIPO IS NULL)ST 
ON (D.GV_TIPO=ST.TIPO)
WHEN NOT MATCHED THEN
INSERT(PK_TIPO, GV_TIPO)
VALUES(SEQ_DIM_TIPO.NEXTVAL,ST.TIPO);
COMMIT;

/****** CARGA DE CATALOGO EDAD **********/

MERGE INTO DIM_EDAD D
USING (SELECT DISTINCT EDAD FROM XINDDL_ST_FLOTA WHERE NOT EDAD IS NULL)ST 
ON (D.GV_EDAD=ST.EDAD)
WHEN NOT MATCHED THEN
INSERT(PK_EDAD, GV_EDAD)
VALUES(SEQ_DIM_EDAD.NEXTVAL,ST.EDAD);
COMMIT;


/****** CARGA DE CATALOGO PAIS **********/

MERGE INTO DIM_PAISES D
USING (SELECT DISTINCT PAIS FROM XINDDL_ST_FLOTA WHERE NOT PAIS IS NULL)ST 
ON (D.GV_PAIS=ST.PAIS)
WHEN NOT MATCHED THEN
INSERT(PK_PAIS, GV_PAIS)
VALUES(SEQ_PK_DIM_PAISES.NEXTVAL,ST.PAIS);
COMMIT;

INSERT INTO FACT_DCS_FLOTA
SELECT
NVL(ANIO,0),
NVL(PK_PAIS,0),
NVL(PK_TIPO,0),
NVL(PK_EDAD,0),
SUM(CANTIDAD)
FROM XINDDL_ST_FLOTA A
LEFT JOIN DIM_PAISES C
ON A.PAIS=C.GV_PAIS
LEFT JOIN DIM_TIPO D
ON A.TIPO=D.GV_TIPO
LEFT JOIN DIM_EDAD E
ON A.EDAD=E.GV_EDAD
GROUP BY 
ANIO,
PK_PAIS,
PK_TIPO,
PK_EDAD;
COMMIT;
